Repository sepandhaghighi/mycoffee, pull requests merged in 2024-10, with the labels that each got.

#27 Fix test
  .github/workflows/test.yml
  CHANGELOG.md
Labels: test

#28 Ratio limits
  CHANGELOG.md
  METHODS.md
  mycoffee/functions.py
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: enhancement

#29 Refactor
  CHANGELOG.md
  mycoffee/functions.py
  test/functions_test.py
Labels: refactoring

#30 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release

#32 Cups bug
  CHANGELOG.md
  README.md
  mycoffee/functions.py
  test/functions_test.py
Labels: bug

#34 Python 3.13
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test

#36 Add/limit gh action run
  .github/workflows/test.yml
  CHANGELOG.md
Labels: test
