Repository sepandhaghighi/mycoffee, pull requests merged in 2024-12, with the labels that each got.

#52 Cup
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#53 Version 0.9
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release

#54 Pint Unit for Water
  AUTHORS.md
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#55 Quart Unit for Water Added
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#56 Fluid Ounce (`fl oz`) Unit for Water Added
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#57 Minor edits
  CHANGELOG.md
  README.md
  test/verified_test.py
Labels: documentation

#58 Version 1.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release

#62 Troy oz unit for water and coffee
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#63 Grains Unit for Water and Coffee
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#65 Carats unit
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#70 CC
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#71 CL
  CHANGELOG.md
  README.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#72 Version 1.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release
