Repository sepandhaghighi/mycoffee, pull requests merged in 2025-01, with the labels that each got.

#73 Troy pounds added for water and coffee
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#75 Grind
  CHANGELOG.md
  README.md
  mycoffee/__main__.py
  mycoffee/functions.py
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: enhancement

#76 Grind limits
  CHANGELOG.md
  mycoffee/functions.py
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: enhancement

#77 `METHODS.md` update
  CHANGELOG.md
  METHODS.md
Labels: documentation

#78 Pennyweights (`dwt`) unit added for water and coffee
  CHANGELOG.md
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: new unit

#79 Minor edits
  mycoffee/__main__.py
  mycoffee/params.py
  test/functions_test.py
Labels: enhancement

#82 Version 1.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release

#84 `README.md` update
  CHANGELOG.md
  README.md
Labels: documentation

#85 Bug fix
  CHANGELOG.md
  mycoffee/functions.py
  test/functions_test.py
Labels: bug

#86 Test
  CHANGELOG.md
  test/functions_test.py
Labels: test, refactoring

#87 Grind type
  CHANGELOG.md
  mycoffee/functions.py
  mycoffee/params.py
  test/functions_test.py
  test/verified_test.py
Labels: enhancement

#88 Input bug fix
  CHANGELOG.md
  mycoffee/__main__.py
  mycoffee/functions.py
  mycoffee/params.py
  test/functions_test.py
Labels: bug

#89 Template
  CHANGELOG.md
  mycoffee/functions.py
  mycoffee/params.py
Labels: refactoring

#90 Version 1.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  mycoffee/params.py
  otherfiles/version_check.py
  setup.py
  test/functions_test.py
Labels: release
